#!/usr/bin/env ruby

readme_final = File.open('README.md', 'w')
readme_base = File.open('_README.md')
readme_base.each_line do |line|
  readme_final.puts line
end

week_readmes = Dir.glob('week*/README.md').sort
week_readmes.each do |week|
  week_file = File.open(week)
  day_files = Dir.glob("\n#{File.dirname(week)}/*/README.md")
  puts day_files
  lines = week_file.readlines
  title = "#{week.split('/')[0].split('-').join(' ')} #{lines[0]}"
  title[0] = title[0].upcase
  title = "[#{title.chomp}](#{week})"
  readme_final.puts "##{title}"
  lines.each do |line|
    if line.index '*'
      readme_final.puts "#{line}"
    end
  end
end
